# Fraxinus GitLab CI/CD configuration file

default:
  #image: olevs/custusx-build-ubuntu2004 #Dockerhub
  image: gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2004

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

.build-variables:
  stage: build
  variables:
    VERSION: ${CI_COMMIT_SHORT_SHA}
    OS: OS
    BASE_DIR: /builds/Fraxinus/$OS #Reusing CX build folders don't work
    GIT_CLONE_PATH: $BASE_DIR/FX/FX #Changes CI_PROJECT_DIR
    BUILD_DIR: $BASE_DIR/CX/build_Release
    CX_SOURCE_PATH: $BASE_DIR/CX/CX

.create-installer:
  script:
    - cd $BUILD_DIR
    # Remove old installer
    - rm -f Fraxinus*.tar.gz
    - cpack
    # The file Fraxinus*.tar.gz should now be in CX/build_Release, and html_pure and html_dev in CX/build_Release/doc
    - cd $CI_PROJECT_DIR
    - mkdir -p $OS/package_artefacts
    - cp -R $BUILD_DIR/Fraxinus*.tar.gz $OS/package_artefacts/
    - cp -R $BUILD_DIR/doc/html_pure $OS/package_artefacts/html_pure/
    - cp -R $BUILD_DIR/doc/html_dev $OS/package_artefacts/html_dev/
    - echo "Compile complete."
  artifacts:
    paths:
      - $OS/package_artefacts/Fraxinus*.tar.gz
      - $OS/package_artefacts/html_pure/
      - $OS/package_artefacts/html_dev/

.reuse-build:
  extends:
    - .build-variables
    - .create-installer
  before_script:
  - echo "Run cxFraxinusPrivateInstaller.py"
  - ls $BASE_DIR
  - test -d $BASE_DIR/CTK/build_Release 
      && eval ./script/cxFraxinusPrivateInstaller.py -s --full -t Release --user_doc --developer_doc --main_branch $CI_COMMIT_BRANCH --gitrepo_main_site_base https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sintef.no/custusx 
      components CustusX Fraxinus FraxinusTracking USSimulator 
      || eval ./script/cxFraxinusPrivateInstaller.py -s --all --full -t Release --user_doc --developer_doc --main_branch $CI_COMMIT_BRANCH --gitrepo_main_site_base https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sintef.no/custusx

build-ubuntu20:
  extends: .reuse-build
  image: gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2004:25.02.02
  variables:
    OS: Ubuntu2004

build-ubuntu22:
  extends: .reuse-build
  image: gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2204:25.02.02
  variables:
    OS: Ubuntu2204

.old-test-job:   # This job runs the Unit + Integration tests
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... "
    - xvfb-run ./script/cxJenkinsMasterBuildScript.py --test_package --main_branch $CI_COMMIT_BRANCH --gitrepo_main_site_base https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sintef.no/custusx
    #Open source:
    #- xvfb-run ./script/cxOpenSourceMasterBuildScript.py --test_package --main_branch $CI_COMMIT_BRANCH --gitrepo_main_site_base https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sintef.no/custusx
    - cp -r /builds/custusx/CustusX/test_results ${CI_PROJECT_DIR}/test_results
  artifacts:
    when: always
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    paths:
      - test_results/*junit.xml
    reports:
      junit: test_results/*junit.xml

.test-job:   # This job runs the Unit + Integration tests
  stage: test    # It only starts when the job in the build stage completes successfully.
  extends: .build-variables
  script:
    - echo "Running unit tests... "
    # Checkout CX repo if missing, else only delete package_artefacts folder
    - test -d $CX_SOURCE_PATH
        && eval rm -rf $CX_SOURCE_PATH/package_artefacts
        || eval git clone -b $CI_COMMIT_BRANCH https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sintef.no/custusx/CustusX.git $CX_SOURCE_PATH
    # Copy installer into CX repository
    - mkdir -p $CX_SOURCE_PATH/package_artefacts
    - cp -R $OS/package_artefacts/Fraxinus*.tar.gz $CX_SOURCE_PATH/package_artefacts/
    - ls $CX_SOURCE_PATH/package_artefacts  2> /dev/null
    - xvfb-run ./script/cxJenkinsMasterBuildScript.py --test_package --main_branch $CI_COMMIT_BRANCH --gitrepo_main_site_base https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sintef.no/custusx
    - cp -R $CX_SOURCE_PATH/test_results ${CI_PROJECT_DIR}/test_results/
  artifacts:
    when: always
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    paths:
      - test_results/*junit.xml
    reports:
      junit: test_results/*junit.xml

test-ubuntu20:
  extends: .test-job
  needs: ["build-ubuntu20"] # Run as soon as previous job is finished
  image: gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2004:25.02.02
  variables:
    OS: Ubuntu2004

test-ubuntu22:
  extends: .test-job
  needs: ["build-ubuntu22"]
  image: gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2204:25.02.02
  variables:
    OS: Ubuntu2204

.deploy:
  stage: deploy
  extends: .build-variables
  environment: production
  script:
  - echo "Deploying application..."
  - cd $CI_PROJECT_DIR/Ubuntu2004/package_artefacts
  - INSTALLER_FILE=$(find Fraxinus*.tar.gz)
  - 'curl
     --header "JOB-TOKEN: $CI_JOB_TOKEN"
     --upload-file $INSTALLER_FILE
     "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Fraxinus/$VERSION/Ubuntu2004/$INSTALLER_FILE"'
  - cd $CI_PROJECT_DIR/Ubuntu2204/package_artefacts
  - INSTALLER_FILE=$(find CustusX*.tar.gz)
  - 'curl
     --header "JOB-TOKEN: $CI_JOB_TOKEN"
     --upload-file $INSTALLER_FILE
     "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Fraxinus/$VERSION/Ubuntu2204/$INSTALLER_FILE"'

deploy-commmit:
  extends: .deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # Only run for changes to the default (develop) branch
      when: never
    - if: '$CI_COMMIT_TAG == null' # Run for all commits, except tags

deploy-tag:
  extends: .deploy
  variables:
    VERSION: ${CI_COMMIT_TAG}
  rules:
    - if: '$CI_COMMIT_TAG != null' # Run if a tag is present (= release or release candidate)

pages:
  stage: deploy
  extends: .build-variables
  environment: production
  script:
    - mv $OS/package_artefacts/html_pure/ public/user_doc/
    - mv $OS/package_artefacts/html_dev/ public/developer_doc/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run for all changes to the default (develop) branch only
